# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddf3ae32bf013378b73f67f27226069e5f78c2ff5254e35f3d446afe522b854bc9f630bb7e2d0928b79758a7f62807b958f96625e3d4209c39ca53b670c28716

test:
  secret_key_base: 26fd9f7da311aaacad0da4f34008399c9d2b1191b2b91de8a363654e7a62f5ad81b7cc8c4e470c14c92cb59657caa0f952131782e36e2539b9b9cadfea771e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
